# Generated by Django 5.1 on 2025-08-19 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizersale',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of bags', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
