# Generated by Django 5.2.5 on 2025-08-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_fertilizersale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='village',
            field=models.CharField(blank=True, choices=[('Dharmasagar', 'Dharmasagar'), ('Somadevarapalli', 'Somadevarapalli'), ('Devnoor', 'Devnoor'), ('Unikicherla', 'Unikicherla'), ('Elukurthy', 'Elukurthy'), ('Saipet', 'Saipet'), ('Kyathamapelli', 'Kyathamapelli'), ('Janakipuram', 'Janakipuram'), ('Velair', 'Velair'), ('Narayanagiri', 'Narayanagiri'), ('Peesara', 'Peesara'), ('Mallikudrla', 'Mallikudrla'), ('Shapalli', 'Shapalli'), ('Gundlasagaram', 'Gundlasagaram'), ('Peddapendyala', 'Peddapendyala'), ('Rampur', 'Rampur'), ('Dharmapur', 'Dharmapur'), ('Mallakapelli', 'Mallakapelli'), ('Ravigudem', 'Ravigudem'), ('Thatikayala', 'Thatikayala')], default='Not Available', max_length=50),
        ),
    ]
